apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front
    tiers: backend
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
      lang: js
  template:
    metadata:
      labels:
        app: front
        lang: js
    spec:
      containers:
      - image: https://github.com/C4RBON73/Mini-Projet_info802_Service.git
        name: front
        ports:
          - containerPort: 80
            name: http
        resources:
          requests:
            cpu: "200m"
            memory: "200Mi"
          limits:
            cpu: "350m"
            memory: "500Mi"
        livenessProbe:
          httpGet:
            path: "/"
            port: 80
