name: Docker Image CI

on:
  push:
    branches: [ "main", "npm", "python" ]
  pull_request:
    branches: [ "main", "npm", "python" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        id: build_image
        run: |
          TIMESTAMP=$(date +%s)
          IMAGE_TAG="info910-js:${TIMESTAMP}"
          REPO_NAME="${{ github.repository }}"
          REPO_NAME_LOWER=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
          docker build . --file Dockerfile --tag ghcr.io/${REPO_NAME_LOWER}/$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push the Docker image
        run: |
          REPO_NAME="${{ github.repository }}"
          REPO_NAME_LOWER=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/${REPO_NAME_LOWER}/$IMAGE_TAG
